version: '3.8'

services:
  app:
    image: rahul870/dockermysql:0.0.1
    ports:
      - 8081:8081
    environment:
      spring_datasource_url: jdbc:mysql://db:3306/localhostSpringboot?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      spring_datasource_username: admin
      spring_datasource_password: root
    depends_on:
      - db


  db:
    image: mysql:8.0.2
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localhostSpringboot
      MYSQL_USER: admin
      MYSQL_PASSWORD: root